### ISSUE TITLE
How to get the paper index

### ISSUE THREAD

**Issue by kingjames1155** [diku-dk/credanno#1]
Thank you for your outstanding contribution. I encountered some problems when running your code. I don't know how to use the Full annotation of cRedAnno+ and Partial annotation ofCRedAnno+(10% b) and cRedAnno+(1% b)in your paper？ 

I ran the following three commands according to your prompts. Which result did I get?  I am wondering whether it is by changing the -- label of the third after running the first two commands_ frac ==（1  ,  0.1  ,    0.01) to get full annotation and 10% ，1%
![image](https://user-images.githubusercontent.com/71316665/209080503-7d3cbb1a-f93b-40e3-bc82-6ac3db7acd17.png)

**Comment by ludles** [comment]
Sorry for the caused confusion. 
- To get results of `1%`, run the command for sparse seeding with `--label_frac 0.01`.
- To get results of `10%`, run the third command with `--label_frac 0.1` **after** sparse seeding.
- The results of full annotation are the same for cRedAnno and cRedAnno+.

Hope this answers your question. Otherwise, feel free to re-open this issue.

**Comment by kingjames1155** [comment]
> Sorry for the caused confusion.
> 
> * To get results of `1%`, run the command for sparse seeding with `--label_frac 0.01`.
> * To get results of `10%`, run the third command with `--label_frac 0.1` **after** sparse seeding.
> * The results of full annotation are the same for cRedAnno and cRedAnno+.
> 
> Hope this answers your question. Otherwise, feel free to re-open this issue.
I really appreciate your answer and thank you again for your outstanding contribution. I understand that if I want to get The results of full annotation, I can directly run the following code and set `-- label_ frac1` ，I don't know if this is right

![image](https://user-images.githubusercontent.com/71316665/209090048-f9779d21-cebf-4499-86f3-65231adc0663.png)

**Comment by ludles** [comment]
> > Sorry for the caused confusion.
> > 
> > * To get results of `1%`, run the command for sparse seeding with `--label_frac 0.01`.
> > * To get results of `10%`, run the third command with `--label_frac 0.1` **after** sparse seeding.
> > * The results of full annotation are the same for cRedAnno and cRedAnno+.
> > 
> > Hope this answers your question. Otherwise, feel free to re-open this issue.
> 
> I really appreciate your answer and thank you again for your outstanding contribution. I understand that if I want to get The results of full annotation, I can directly run the following code and set `-- label_ frac1` ，I don't know if this is right
> 
> ![image](https://user-images.githubusercontent.com/71316665/209090048-f9779d21-cebf-4499-86f3-65231adc0663.png)

Yes. That's it.
